// Bootstrap a consumer project so it can run the agent-memory sidecar
// without hand-writing compose/env/gitignore plumbing. Idempotent: running
// it twice is always safe (existing files are preserved unless --force).
//
// Target files (all inside the caller's current working directory):
//   - docker-compose.agent-memory.yml  — standalone compose (Pattern A)
//   - .env.agent-memory                — environment overrides (optional)
//   - .gitignore                       — marker-delimited section appended
//
// The command is pure I/O plus the embedded templates; no DB access, no
// network, no side-effects outside `cwd`. A1 · runtime-trust.

import { access, constants, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

export const GITIGNORE_MARKER_START = "# >>> agent-memory (managed by `memory init`)";
export const GITIGNORE_MARKER_END = "# <<< agent-memory";
export const GITIGNORE_PATTERNS = [".env.agent-memory"];

export const DOCKER_COMPOSE_TEMPLATE = `# Generated by \`memory init\` — drop-in sidecar for any stack.
# See docs/consumer-setup-docker-sidecar.md for merge patterns.
services:
  agent-memory-postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_DB: agent_memory
      POSTGRES_USER: memory
      POSTGRES_PASSWORD: memory_dev
    volumes:
      - agent-memory-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U memory -d agent_memory"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - agent-memory

  agent-memory:
    image: ghcr.io/event4u-app/agent-memory:latest
    depends_on:
      agent-memory-postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://memory:memory_dev@agent-memory-postgres:5432/agent_memory
      REPO_ROOT: /workspace
      LOG_LEVEL: \${LOG_LEVEL:-info}
    volumes:
      - .:/workspace:ro
    # Image default is \`memory serve\` — supervisor loop that applies
    # migrations on startup (ADR-0002). Opt out with MEMORY_AUTO_MIGRATE=false.
    healthcheck:
      test: ["CMD", "memory", "health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - agent-memory

networks:
  agent-memory:
    name: agent-memory

volumes:
  agent-memory-pgdata:
`;

export const PROJECT_CONFIG_TEMPLATE = `# agent-memory project config (C1 · runtime-trust).
#
# Precedence: CLI flag > ENV > this file > built-in default.
# Validated against \`schema/agent-memory-config-v1.schema.json\` — an invalid
# file makes every \`memory\` command exit 1 with a clear error.
#
# Uncomment what you want to commit to the repo. Anything you leave out
# stays controllable via ENV or --flag.

version: 1

# Stable identifier for retrieval filters and PR-integration (C2/C3).
# repository: acme/checkout

# trust:
#   threshold: 0.6       # minimum trust score for retrieval (0..1)
#   threshold_low: 0.3   # lower threshold for low-trust mode

# retrieval:
#   token_budget: 2000   # progressive-disclosure cap (100..50000)

# embedding:
#   provider: bm25-only  # local | gemini | openai | voyage | bm25-only

# decay:
#   profile: default     # default | conservative | aggressive

# C2 policy-engine knobs. Absence = policy disabled.
# policies:
#   fail_on_contradicted_critical: true
#   fail_on_invalidated_adr: true
#   min_trust_for_type:
#     architecture_decision: 0.7
#   block_on_poisoned_referenced: true
`;

export const ENV_TEMPLATE = `# agent-memory overrides (picked up by \`docker compose --env-file\`).
# Uncomment the lines you want to change; defaults match the built-in
# compose service names.

# DATABASE_URL=postgresql://memory:memory_dev@agent-memory-postgres:5432/agent_memory

# Embedding provider (local|gemini|openai|voyage|bm25-only).
# EMBEDDING_PROVIDER=local
# GEMINI_API_KEY=
# OPENAI_API_KEY=
# VOYAGE_API_KEY=

# Trust & retrieval tuning.
# MEMORY_TRUST_THRESHOLD_DEFAULT=0.6
# MEMORY_TOKEN_BUDGET=2000

# HTTP surface in \`memory serve\` (set to a port to enable /health and /ready).
# MEMORY_HTTP_PORT=7077

# Verbosity.
# LOG_LEVEL=info
`;

export type InitFileStatus = "created" | "skipped" | "updated";

export interface InitFileResult {
	path: string;
	status: InitFileStatus;
	reason?: string;
}

export interface InitReport {
	status: "ok";
	cwd: string;
	files: InitFileResult[];
}

export interface InitOptions {
	cwd?: string;
	force?: boolean;
}

async function exists(path: string): Promise<boolean> {
	try {
		await access(path, constants.F_OK);
		return true;
	} catch {
		return false;
	}
}

async function writeIfMissing(
	path: string,
	contents: string,
	force: boolean,
): Promise<InitFileResult> {
	if ((await exists(path)) && !force) {
		return { path, status: "skipped", reason: "already exists" };
	}
	await writeFile(path, contents, "utf8");
	return { path, status: "created" };
}

export function applyGitignoreBlock(existing: string): { content: string; changed: boolean } {
	const block = [GITIGNORE_MARKER_START, ...GITIGNORE_PATTERNS, GITIGNORE_MARKER_END, ""].join(
		"\n",
	);
	if (existing.includes(GITIGNORE_MARKER_START)) {
		return { content: existing, changed: false };
	}
	const prefix = existing.length === 0 || existing.endsWith("\n") ? existing : `${existing}\n`;
	return { content: `${prefix}${block}`, changed: true };
}

async function applyGitignore(path: string): Promise<InitFileResult> {
	const existed = await exists(path);
	const previous = existed ? await readFile(path, "utf8") : "";
	const { content, changed } = applyGitignoreBlock(previous);
	if (!changed) {
		return { path, status: "skipped", reason: "marker already present" };
	}
	await writeFile(path, content, "utf8");
	return existed
		? { path, status: "updated", reason: "marker appended" }
		: { path, status: "created" };
}

export async function runInit(options: InitOptions = {}): Promise<InitReport> {
	const cwd = options.cwd ?? process.cwd();
	const force = options.force ?? false;
	const files: InitFileResult[] = [];
	files.push(
		await writeIfMissing(
			join(cwd, "docker-compose.agent-memory.yml"),
			DOCKER_COMPOSE_TEMPLATE,
			force,
		),
	);
	files.push(await writeIfMissing(join(cwd, ".env.agent-memory"), ENV_TEMPLATE, force));
	files.push(await writeIfMissing(join(cwd, ".agent-memory.yml"), PROJECT_CONFIG_TEMPLATE, force));
	files.push(await applyGitignore(join(cwd, ".gitignore")));
	return { status: "ok", cwd, files };
}

export function renderInitSummary(report: InitReport): string {
	const lines = [`agent-memory init → ${report.cwd}`];
	for (const f of report.files) {
		const marker = f.status === "created" ? "+" : f.status === "updated" ? "~" : "=";
		const suffix = f.reason ? ` (${f.reason})` : "";
		lines.push(`  ${marker} ${f.path}${suffix}`);
	}
	return lines.join("\n");
}
