/**
 * Generate the machine-readable appendix of docs/cli-reference.md from
 * the Commander program in src/cli/index.ts.
 *
 * Contract with the doc:
 *   - Hand-written narrative (preamble + topical sections) stays as-is.
 *   - Between the two markers below, this script is the source of truth.
 *
 *   <!-- GEN:CLI-REFERENCE:START -->
 *   <!-- GEN:CLI-REFERENCE:END -->
 *
 * Run with: `npm run docs:cli`. CI runs the same command and fails if
 * `git diff --exit-code docs/cli-reference.md` is non-empty (P4-2).
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import type { Command, Option } from "commander";
import { program } from "../src/cli/index.js";

const MARKER_START = "<!-- GEN:CLI-REFERENCE:START -->";
const MARKER_END = "<!-- GEN:CLI-REFERENCE:END -->";
const DOC_PATH = resolve(process.cwd(), "docs/cli-reference.md");

type FlagRow = {
	flag: string;
	required: boolean;
	repeatable: boolean;
	defaultValue: string;
	description: string;
};

function describeDefault(opt: Option): string {
	const d = opt.defaultValue;
	if (d === undefined || d === null) return "—";
	if (Array.isArray(d))
		return d.length === 0 ? "—" : `\`${JSON.stringify(d)}\``;
	if (typeof d === "boolean") return d ? "`true`" : "off";
	return `\`${String(d)}\``;
}

function rowsForOptions(cmd: Command): FlagRow[] {
	// Commander stores required and optional flags in the same array;
	// the `required` bit is set only via .requiredOption().
	const opts = (cmd.options ?? []) as Option[];
	return opts.map((o) => ({
		flag: o.flags,
		required: !!o.mandatory,
		repeatable:
			typeof o.parseArg === "function" && o.defaultValue !== undefined
				? Array.isArray(o.defaultValue)
				: false,
		defaultValue: describeDefault(o),
		description: o.description || "",
	}));
}

type ArgInfo = { name: string; required: boolean; description: string };

function argInfos(cmd: Command): ArgInfo[] {
	// Commander exposes registered arguments on `_args` (untyped public surface).
	// Fall back to the usage string if the internal shape changes.
	const rawArgs = (cmd as unknown as { registeredArguments?: unknown[] })
		.registeredArguments;
	if (!Array.isArray(rawArgs)) return [];
	return rawArgs.map((a) => {
		const arg = a as {
			_name?: string;
			required?: boolean;
			description?: string;
		};
		return {
			name: arg._name ?? "arg",
			required: !!arg.required,
			description: arg.description ?? "",
		};
	});
}

function usageLine(cmd: Command): string {
	const parts: string[] = [`memory ${cmd.name()}`];
	for (const a of argInfos(cmd)) {
		parts.push(a.required ? `<${a.name}>` : `[${a.name}]`);
	}
	if ((cmd.options ?? []).length > 0) parts.push("[options]");
	return parts.join(" ");
}

function renderCommand(cmd: Command): string {
	const lines: string[] = [];
	lines.push(`### \`${cmd.name()}\``);
	lines.push("");
	if (cmd.description()) {
		lines.push(cmd.description());
		lines.push("");
	}
	lines.push("```bash");
	lines.push(usageLine(cmd));
	lines.push("```");
	lines.push("");

	const args = argInfos(cmd);
	if (args.length > 0) {
		lines.push("**Arguments**");
		lines.push("");
		lines.push("| Name | Required | Description |");
		lines.push("|---|---|---|");
		for (const a of args) {
			lines.push(
				`| \`<${a.name}>\` | ${a.required ? "yes" : "no"} | ${a.description || "—"} |`,
			);
		}
		lines.push("");
	}

	const rows = rowsForOptions(cmd);
	if (rows.length > 0) {
		lines.push("**Options**");
		lines.push("");
		lines.push("| Flag | Required | Default | Description |");
		lines.push("|---|---|---|---|");
		for (const r of rows) {
			lines.push(
				`| \`${r.flag}\` | ${r.required ? "yes" : "no"} | ${r.defaultValue} | ${r.description || "—"} |`,
			);
		}
		lines.push("");
	}

	return lines.join("\n");
}

function renderAppendix(): string {
	const body: string[] = [];
	body.push("## Command reference (generated)");
	body.push("");
	body.push("This appendix is regenerated by `npm run docs:cli` from the");
	body.push("Commander program in [`src/cli/index.ts`](../src/cli/index.ts).");
	body.push(
		"It lists every command, argument, flag, default, and required-ness",
	);
	body.push(
		"the real CLI accepts. If this section and the code disagree, the code",
	);
	body.push("wins — the CI drift guard will fail the build.");
	body.push("");
	const commands = [...program.commands].sort((a, b) =>
		a.name().localeCompare(b.name()),
	);
	for (const cmd of commands) body.push(renderCommand(cmd));
	return body.join("\n");
}

function main(): void {
	const current = readFileSync(DOC_PATH, "utf8");
	const startIdx = current.indexOf(MARKER_START);
	const endIdx = current.indexOf(MARKER_END);
	if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
		throw new Error(
			`Missing generator markers in ${DOC_PATH}. Expected ${MARKER_START} ... ${MARKER_END}`,
		);
	}
	const before = current.slice(0, startIdx + MARKER_START.length);
	const after = current.slice(endIdx);
	const generated = renderAppendix();
	const next = `${before}\n\n${generated}\n${after}`;
	writeFileSync(DOC_PATH, next);
	const commandCount = program.commands.length;
	console.log(
		`✅ docs/cli-reference.md: regenerated appendix for ${commandCount} commands`,
	);
}

main();
