/**
 * Generate the machine-readable section of docs/secret-safety.md from
 * the pattern catalog in src/security/secret-patterns.ts.
 *
 * Contract with the doc:
 *   - Hand-written narrative (preamble, policy explanation) stays as-is.
 *   - Between the two markers below, this script is the source of truth.
 *
 *   <!-- GEN:SECRET-PATTERNS:START -->
 *   <!-- GEN:SECRET-PATTERNS:END -->
 *
 * Run with: `npm run docs:secrets`. CI runs the same command and fails
 * if `git diff --exit-code docs/secret-safety.md` is non-empty (II1
 * drift-guard).
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
	CATALOG_VERSION,
	SECRET_PATTERNS,
	type SecretPattern,
} from "../src/security/secret-patterns.js";

const MARKER_START = "<!-- GEN:SECRET-PATTERNS:START -->";
const MARKER_END = "<!-- GEN:SECRET-PATTERNS:END -->";
const DOC_PATH = resolve(process.cwd(), "docs/secret-safety.md");

function escapeMd(value: string): string {
	return value.replace(/\|/g, "\\|");
}

function hintList(p: SecretPattern): string {
	if (!p.falsePositiveHints || p.falsePositiveHints.length === 0) return "—";
	return p.falsePositiveHints.map((h) => escapeMd(h)).join("; ");
}

function renderTable(patterns: readonly SecretPattern[]): string {
	const grouped = new Map<string, SecretPattern[]>();
	for (const p of patterns) {
		const list = grouped.get(p.provider) ?? [];
		list.push(p);
		grouped.set(p.provider, list);
	}
	const providers = [...grouped.keys()].sort((a, b) => a.localeCompare(b));

	const lines: string[] = [];
	lines.push(`**Catalog version:** \`${CATALOG_VERSION}\` · `);
	lines.push(`**Total patterns:** ${patterns.length} · `);
	lines.push(`**Providers:** ${providers.length}`);
	lines.push("");
	lines.push("| Provider | Name | Code | Confidence | Description | Known false positives |");
	lines.push("|---|---|---|---|---|---|");
	for (const provider of providers) {
		const rows = grouped.get(provider) ?? [];
		for (const p of rows) {
			lines.push(
				`| \`${provider}\` | \`${p.name}\` | \`${p.code}\` | ${p.confidence} | ${escapeMd(p.description)} | ${hintList(p)} |`,
			);
		}
	}
	lines.push("");
	return lines.join("\n");
}

function renderSection(): string {
	const body: string[] = [];
	body.push("## Pattern catalog (generated)");
	body.push("");
	body.push("This section is regenerated by `npm run docs:secrets` from");
	body.push(
		"[`src/security/secret-patterns.ts`](../src/security/secret-patterns.ts).",
	);
	body.push(
		"If this table and the catalog disagree, the catalog wins — CI fails on drift.",
	);
	body.push("");
	body.push(renderTable(SECRET_PATTERNS));
	body.push(
		"Patterns with `confidence: medium` may be neutralised by the allow-list",
	);
	body.push(
		"(roadmap II4) in contexts where the match is demonstrably a non-secret",
	);
	body.push("(UUIDs, commit SHAs, public content hashes).");
	return body.join("\n");
}

function main(): void {
	const current = readFileSync(DOC_PATH, "utf8");
	const startIdx = current.indexOf(MARKER_START);
	const endIdx = current.indexOf(MARKER_END);
	if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
		throw new Error(
			`Missing generator markers in ${DOC_PATH}. Expected ${MARKER_START} … ${MARKER_END}`,
		);
	}
	const before = current.slice(0, startIdx + MARKER_START.length);
	const after = current.slice(endIdx);
	const generated = renderSection();
	const next = `${before}\n\n${generated}\n${after}`;
	writeFileSync(DOC_PATH, next);
	console.log(
		`✅ docs/secret-safety.md: regenerated catalog table for ${SECRET_PATTERNS.length} patterns (v${CATALOG_VERSION})`,
	);
}

main();
