import type { EvidenceRepository } from "../db/repositories/evidence.repository.js";
import type { MemoryEntryRepository } from "../db/repositories/memory-entry.repository.js";
import type { EmbeddingFallbackChain } from "../embedding/index.js";
import type { ContradictionService } from "../trust/contradiction.service.js";
import { logger } from "../utils/logger.js";
import { classifyCandidate, type IngestionCandidate } from "./candidate.js";
import { ExtractionGuard, type ExtractionGuardOptions } from "./extraction-guard.js";
import { applyPrivacyFilter } from "./privacy-filter.js";
import { readDocs } from "./scanners/doc-reader.js";
import { scanFiles } from "./scanners/file-scanner.js";
import { readGitCommits } from "./scanners/git-reader.js";

export interface IngestionResult {
	/** Total candidates generated by scanners */
	totalCandidates: number;
	/** Entries created (in quarantine) */
	createdEntries: number;
	/** Contradictions detected during ingestion */
	contradictionsDetected: number;
	/** Whether extraction guard blocked ingestion */
	guardBlocked: boolean;
	/** Created entry IDs */
	entryIds: string[];
}

export interface PipelineOptions {
	root: string;
	repository: string;
	/** Run extraction guard before ingestion */
	guardOptions?: ExtractionGuardOptions;
	/** Skip specific scanners */
	skipScanners?: ("files" | "docs" | "git")[];
	/** Max files for file scanner */
	maxFiles?: number;
	/** Git reader: max commits */
	maxCommits?: number;
	/** Git reader: only since date */
	since?: string;
}

/**
 * Full ingestion pipeline:
 * 1. Extraction guard (block if tests fail)
 * 2. Run scanners (files, docs, git)
 * 3. Privacy filter on all candidates
 * 4. Auto-classify (impact, knowledge class, tier)
 * 5. Create entries in quarantine
 * 6. Attach evidence
 * 7. Contradiction detection
 */
export class IngestionPipeline {
	constructor(
		private readonly entryRepo: MemoryEntryRepository,
		private readonly evidenceRepo: EvidenceRepository,
		private readonly contradictionService: ContradictionService,
		/** Optional — if provided, entries are embedded via the fallback chain. */
		private readonly embeddingChain?: EmbeddingFallbackChain,
	) {}

	async run(options: PipelineOptions): Promise<IngestionResult> {
		const skip = new Set(options.skipScanners ?? []);

		// 1. Extraction guard
		if (options.guardOptions) {
			const guard = new ExtractionGuard(options.guardOptions);
			const guardResult = await guard.check();
			if (!guardResult.allowed) {
				logger.warn({ reason: guardResult.reason }, "Ingestion blocked by extraction guard");
				return {
					totalCandidates: 0,
					createdEntries: 0,
					contradictionsDetected: 0,
					guardBlocked: true,
					entryIds: [],
				};
			}
		}

		// 2. Run scanners in parallel
		const scannerResults = await Promise.all([
			!skip.has("files")
				? scanFiles({
						root: options.root,
						repository: options.repository,
						maxFiles: options.maxFiles,
					})
				: [],
			!skip.has("docs") ? readDocs({ root: options.root, repository: options.repository }) : [],
			!skip.has("git")
				? readGitCommits({
						root: options.root,
						repository: options.repository,
						maxCommits: options.maxCommits,
						since: options.since,
					})
				: [],
		]);
		const allCandidates = scannerResults.flat();

		logger.info({ totalCandidates: allCandidates.length }, "Scanners complete, starting ingestion");

		// 3–7. Process each candidate
		const entryIds: string[] = [];
		let contradictions = 0;

		for (const candidate of allCandidates) {
			// 3. Privacy filter
			const filtered = applyCandidatePrivacyFilter(candidate);

			// 4. Auto-classify
			const classification = classifyCandidate(filtered);

			// 5. Create entry (in quarantine). Embedding computed lazily via fallback chain.
			let embedding: number[] | undefined;
			if (this.embeddingChain) {
				const { vector } = await this.embeddingChain.embed(filtered.embeddingText);
				if (vector.length > 0) embedding = vector;
			}
			const entry = await this.entryRepo.create({
				type: filtered.type,
				title: filtered.title,
				summary: filtered.summary,
				details: filtered.details,
				scope: filtered.scope,
				impactLevel: classification.impactLevel,
				knowledgeClass: classification.knowledgeClass,
				consolidationTier: classification.consolidationTier,
				embeddingText: filtered.embeddingText,
				embedding,
				createdBy: `system:${filtered.source}`,
			});

			// 6. Attach evidence
			for (const ev of filtered.evidence) {
				await this.evidenceRepo.create({
					memoryEntryId: entry.id,
					kind: ev.kind,
					ref: ev.ref,
					details: ev.details,
				});
			}

			// 7. Contradiction detection
			const detected = await this.contradictionService.detectContradictions(entry);
			contradictions += detected.length;

			entryIds.push(entry.id);
		}

		logger.info({ created: entryIds.length, contradictions }, "Ingestion pipeline complete");

		return {
			totalCandidates: allCandidates.length,
			createdEntries: entryIds.length,
			contradictionsDetected: contradictions,
			guardBlocked: false,
			entryIds,
		};
	}
}

function applyCandidatePrivacyFilter(candidate: IngestionCandidate): IngestionCandidate {
	return {
		...candidate,
		title: applyPrivacyFilter(candidate.title),
		summary: applyPrivacyFilter(candidate.summary),
		details: candidate.details ? applyPrivacyFilter(candidate.details) : undefined,
		embeddingText: applyPrivacyFilter(candidate.embeddingText),
	};
}
